"""ORINOX v2 Communication Agent — Gmail MCP for real email delivery"""
import json, time
from tools.registry import get_registry
from db.database import get_db


class CommsAgent:
    name = "COMMS_AGENT"

    async def execute(self, action, params, workflow_id=None, step=0):
        reg, db = get_registry(), await get_db()
        start = time.time()
        if workflow_id:
            await db.log_step(workflow_id, step, self.name, action,
                              input_summary=json.dumps(params, default=str)[:500], status="running")
        try:
            result = await self._route(action, params, reg)
            ms = int((time.time() - start) * 1000)
            if workflow_id:
                await db.log_step(workflow_id, step, self.name, action,
                    output_summary=json.dumps(result, default=str)[:500],
                    status="completed", duration_ms=ms)
            return {"agent": self.name, "action": action, "result": result, "duration_ms": ms}
        except Exception as e:
            if workflow_id:
                await db.log_step(workflow_id, step, self.name, action,
                                  status="failed", error_message=str(e))
            return {"agent": self.name, "action": action, "error": str(e)}

    async def _route(self, action, params, reg):
        if action in ("generate_advisory", "comms_generate_advisory"):
            return await reg.call("comms_generate_advisory", **params)
        elif action in ("queue_and_log", "comms_queue_and_log"):
            return await reg.call("comms_queue_and_log", **params)
        elif action in ("generate_batch", "comms_generate_batch"):
            return await reg.call("comms_generate_batch", **params)
        return {"error": f"Unknown action: {action}"}

    async def email_segment(self, clients, event_summary, event_id=None,
                            workflow_id=None, step=0):
        """Generate + send advisory emails to all impacted clients. Core hero demo."""
        reg, db = get_registry(), await get_db()

        # Generate batch template
        template = await reg.call("comms_generate_batch",
                                  clients=clients, event_summary=event_summary)
        subject = template.get("subject", "Market Advisory")
        body = template.get("body", "Dear {client_name}, please contact your RM.")

        # Send to each client
        sent = []
        for client in clients:
            result = await reg.call("comms_queue_and_log",
                client=client, subject=subject, body=body,
                event_id=event_id, workflow_id=workflow_id)
            sent.append(result)

        summary = {"total_sent": len(sent), "messages": sent}
        by_status = {}
        for s in sent:
            st = s.get("status", "unknown")
            by_status[st] = by_status.get(st, 0) + 1
        summary["by_status"] = by_status

        if workflow_id:
            await db.log_step(workflow_id, step, self.name, "email_segment",
                output_summary=f"Emailed {len(sent)} clients: {by_status}",
                status="completed")
        return summary

    async def send_research_query(self, query, context=None, workflow_id=None, step=0):
        """Send research query to research team via Gmail."""
        reg, db = get_registry(), await get_db()

        subject = f"Research Query: {query[:60]}"
        body = f"""Research Query from RM Vikram

Query: {query}
{f'Context: {context}' if context else ''}

Submitted: auto-generated by ORINOX
Please reply to this thread with your analysis.

---
This is an automated query from the ORINOX wealth advisory system."""

        result = await reg.call("gmail_send_email",
            to="research-desk@company.com",
            subject=subject, body=body)

        tracking_id = f"RQ-{int(time.time())}"
        await db.log_interaction({
            "client_id": "system",
            "interaction_type": "research_query",
            "channel": "email",
            "subject": subject,
            "summary": query[:200],
            "logged_by": "comms_agent"})

        if workflow_id:
            await db.log_step(workflow_id, step, self.name, "send_research_query",
                output_summary=f"Research query sent: {tracking_id}",
                status="completed")

        return {"tracking_id": tracking_id, "query": query,
                "status": result.get("status"), "via": result.get("via")}
